### ISSUE TITLE
Link refering destructhub repository is broken

### ISSUE THREAD

**Issue by ryukinix** [rafaelcn/louv1.1x#1]
Take a look on README.md.

**Comment by rafaelcn** [comment]
Thank you, gonna fix that later

## 

Regards,
Rafael Campos Nunes.
rafaelnunes737@hotmail.commailto:rafaelnunes737@hotmail.com

Le 24 oct. 2016 ? 11:43, "Manoel Machado" <notifications@github.com<mailto:notifications@github.com>> a ?crit :

Take a look on README.md.

##

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
